# Generated by Django 5.0.3 on 2024-03-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.TextField(choices=[('MATH', 'Math Facts Practice'), ('ANAGRAM', 'Anagram Hunt')], default='MATH')),
                ('score', models.IntegerField()),
                ('word_length', models.CharField(blank=True, choices=[('3', '3 letter words'), ('4', '4 letter words'), ('5', '5 letter words'), ('6', '6 letter words'), ('7', '7 letter words'), ('8', '8 letter words')], max_length=20, null=True)),
                ('total_words', models.IntegerField(blank=True, null=True)),
                ('operation', models.CharField(blank=True, choices=[('+', 'Addition'), ('-', 'Subtraction'), ('x', 'Multiplication'), ('/', 'Division')], max_length=20, null=True)),
                ('max_number', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
